name: doda_work
description: "this is servcice provider app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shimmer:
  url_launcher: ^6.3.1
  pin_code_fields:
  loading_animation_widget:
  http_parser: ^4.0.2
  mime: ^1.0.4
  flutter_screenutil: ^5.9.3
  flutter_animate:
  get:
  get_storage:
  connectivity_plus:
  flutter_svg:
  country_picker: ^2.0.27
  intl: ^0.19.0
  image_picker:
  socket_io_client: ^3.1.3
  flutter_rating_bar: ^4.0.1
  http:
  cached_network_image: ^3.4.1
  shadify: ^1.0.1
  infinite_scroll_pagination: ^4.1.0
  flutter_datetime_picker_plus: ^2.2.0
  google_maps_flutter: ^2.13.1
  flutter_html: ^3.0.0
  dio: ^5.4.0
  firebase_core: ^4.0.0
  firebase_auth: ^6.1.2
  google_sign_in: ^6.1.2
  fluttertoast: ^9.0.0
  sign_in_with_apple: ^7.0.1
  flutter_image_compress :
  webview_flutter: ^4.13.0
  google_fonts: ^6.1.0
  my_location_picker: ^1.0.0
  geolocator: ^10.1.1

  animated_toggle_switch: ^0.8.7


dev_dependencies:
  change_app_package_name: ^1.4.0
  rename_app: ^1.6.5



  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:

  # dart run rename_app:main all="My App Name"
  # flutter pub run change_app_package_name:main net.appdevs.carbo

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/dummy/
